### ISSUE TITLE
Update with Pitt CS wiki Problem set?

### ISSUE THREAD

**Issue by Zmwang622** [Richie78321/tech-interview-prep-guide#1]
My main concern w the Tech interview handbook's problems is that it ends up cramming a lot of pretty tough problem into one week. The problems are really good, but for me it gives the illusion that you can realistically do all the problems in one week. 

IMO it is possible esp if you have algorithms experience and shit, but for beginners it def gives the wrong impression. Ex: Week 2's problems like Container with Most Water, Longest Repeating Char Replacement, Longest Substring without Repeating Char, Minimum Window Substring, and Palindromic substrings are all very difficult problems. But there are 7 additional problems to those for that week. I am certain that a beginner (esp someone who is on week 2) will get overwhelmed by the sheer number of questions.

Also Simon just turned the week-by-week study plan I've been sending into a Wiki guide so we could link to that as well. The first 12 week's problems are identical (i add bonuses too) but I also added 3 extra weeks of other topics that could be useful. View PR [here](https://github.com/PittCSWiki/pittcswiki/pull/297) 

Finally, Mat and I wrote up some plans last year in the [Acing Your Interview](https://pittcs.wiki/zero-to-offer/ace-your-interview/#making-a-plan) guide. We should find a way to merge your guide together with what we wrote there. The Ace your interview's paragraphs were pretty rushed and low quality anyways.

**Comment by Richie78321** [comment]
Yeah I agree, I definitely don't do the listed problems in one week's time. I appreciate the concerns here, but this guide is just a personal and opinionated one that I threw on GitHub in case anyone wanted to see it.

**Comment by Zmwang622** [comment]
oh word i thought you were turning it to a wiki guide

**Comment by Richie78321** [comment]
Ahh gotcha my bad
